### ISSUE TITLE
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity

### ISSUE THREAD

**Issue by hespanha** [eXamadeus/godaddypy#6] opened 2018-08-18 07:34 UTC
I'm able to connect to the server, but when I call "client.update_ip" I get the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/godaddypy/client.py", line 96, in _validate_response_success
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.godaddy.com/v1/domains/casahespanha.com/records/A/@

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./godaddypy-dyndns.py", line 48, in <module>
    rc=client.update_ip(public_ip, domains=[domain])
  File "/usr/local/lib/python3.5/dist-packages/godaddypy/client.py", line 245, in update_ip
    self.update_record(domain, record)
  File "/usr/local/lib/python3.5/dist-packages/godaddypy/client.py", line 299, in update_record
    self._put(url, json=record)
  File "/usr/local/lib/python3.5/dist-packages/godaddypy/client.py", line 66, in _put
    return self._request_submit(requests.put, url=url, json=json, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/godaddypy/client.py", line 82, in _request_submit
    self._validate_response_success(resp)
  File "/usr/local/lib/python3.5/dist-packages/godaddypy/client.py", line 98, in _validate_response_success
    raise BadResponse(response.json())
godaddypy.client.BadResponse: Response Data: {'fields': [{'path': 'records', 'message': 'is not a array', 'code': 'UNEXPECTED_TYPE'}], 'message': "Request body doesn't fulfill schema, see details in `fields`", 'code': 'INVALID_BODY'}

This happens even with the code in the README.rst example

Any idea what the problem could be?

**Comment by eXamadeus** [comment] 2018-10-19 13:48
Interesting, I haven't checked this yet, but if what you are saying is true it might be an update to the GoDaddy API.  I'll check it tonight when I get off work, and post back here with my findings.

**Comment by eXamadeus** [comment] 2018-10-22 17:33
So I can't reproduce this issue.  I am assuming this has to do with a bad library version?

What is the output of `pip list`?

**Comment by eXamadeus** [comment] 2018-10-22 17:39
I deleted my earlier comment, this is a 400/500 error coming from godaddy.  Can you provide the parameters you are sending into the method?

The error hints at what is wrong:

- path: records
- message: is not a array
- code: UNEXPECTED_TYPE

and

- code: INVALID_BODY
- message: Request body doesn't fulfill schema, see details in fields

**Comment by eXamadeus** [comment] 2018-10-22 17:39
~Closing due to being unrelated to the GoDaddyPy.  Error message should be sufficient.~

EDIT: Sorry, my brain has been scattered lately.  I should have linked it to this earlier, this may be related to #3.  Please check and make sure you're using the latest version of GoDaddyPy.  Regardless, I am still closing the issue as it can be resolved with an upgrade.

**Closed as completed by eXamadeus** 2018-10-22 17:39 UTC
